on:
  push:
    branches: ["deployment"]
    
name: Build and Push Docker Image

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/shmbackend:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/shmbackend:${{ github.sha }}
